import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.scss";
import { fetchMovies } from "../src/helper";

//
import * as React from "react";
import AppBar from "@mui/material/AppBar";
import Box from "@mui/material/Box";
import Toolbar from "@mui/material/Toolbar";
import Typography from "@mui/material/Typography";
import Button from "@mui/material/Button";
import IconButton from "@mui/material/IconButton";
import MenuIcon from "@mui/icons-material/Menu";

// components

import NavBar from "../src/components/NavBar/NavBar";
import TopMovie from "../src/components/TopMovie/TopMovie";
import MovieList from "../src/components/MovieList/MovieList";

export default function Home({ topMovie, movieList }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.content}>
        <NavBar />
        <TopMovie topMovie={topMovie} />
        <MovieList title={"Popular"} allMovies={movieList.popular} />
        <MovieList title={"Top Rated"} allMovies={movieList.topRated} />
        <MovieList title={"Upcoming"} allMovies={movieList.upcoming} />
      </div>
    </div>
  );
}

export async function getServerSideProps() {
  const data = await fetchMovies();

  const { topMovie, movieList } = data;

  return {
    props: { topMovie, movieList },
  };
}
